version: '3'

services:
  apache_php:
    build: ./httpd
    ports:
      - 8080:8080
    volumes:
      - ./httpd/src:/var/www/html
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      APACHE_HOSTNAME1: "WebServer1"

  mariadb:
    build: ./mySQL
    ports:
      - 3306:3306
    volumes:
      - ./mySQL:/var/lib/mysql
    environment:
      MYSQL_HOSTNAME: "mariaDB"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "rootroot"
      MYSQL_DATABASE: "my_database"
      MYSQL_ROOT_PASSWORD: "rootroot"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_CHARSET: "cp1251"
      MYSQL_COLLATION: "cp1251_bin"

  apache_load_balancer:
    build: ./balancer
    ports:
      - 80:80
    volumes:
      - ./balancer/src:/var/www/html
    links:
      - mariadb
      - apache_php
    depends_on:
      - apache_php
    environment:
      APACHE_HOSTNAME2: "WebServer2"
